### PR TITLE
Invitees component for Event Edit

### LINKED ISSUE #75: Event Invitees Component
Create a reusable list component to show the invitees. (In the future we will probably have a second list of just collaborators). 

As part of this include the add invitee button as well as hook up the modal. 

Invitees

### LINKED ISSUE #76: Create an add invitee modal
This isn't included in the designs, but on the event editor, we will need a button to add a new person who is invited. When you click on the button, a modal will open and you can type the username. Then there should be an add(primary button) and cancel (secondary button). If you click add, then the person should appear in the list.

### PR DESCRIPTION
**Pull request by hokansom**
Created the Invitees section for the event edit. The component includes two different versions to account for the viewers and the collaborators. 

I'm not sure how I feel about the theme button colors, we may want to update those to either be the accent color or maybe match the event color. (We can make a decision once we put the page together). 

NOTE: I branched off of the add invitee modal branch, so for this particular pr, you can look at the last 2 commits. 

Screen Shot 2020-10-30 at 6 00 22 PM

Closes #75; Closes #76

### CODE REVIEW

**Comment by josiahsrc** [comment]
The UI looks great, though I think right-justified accent-colored buttons might look better here

**Review by josiahsrc — APPROVED** [review]
Looks great code-wise. Only that one comment on the button.

**Comment by hokansom** [comment]
Switched to right-aligned and accent buttons. 

Screen Shot 2020-10-31 at 11 27 34 AM

Screen Shot 2020-10-31 at 11 27 58 AM

**Review by josiahsrc — APPROVED** [review]

**Comment by josiahsrc** [comment]
This looks awesome. Approved, merge when ready 🚀

**Pull request merged**
