### PR TITLE
Event edit functionality

### LINKED ISSUE #82: Add event edit functionality
Event Editor (Invitation Accepted) - About

Add all of the separate components together and add any required functionality.

### LINKED ISSUE #109: Update frontend to reflect changes in schema
Some of the schemas have changed. For example, eventName is now title. Go through the existing code and make sure everything matches the updated schema and pages are working as expected.

### PR DESCRIPTION
**Pull request by hokansom**
You can edit any of the fields of an existing event, and it properly saves on the backend. So the changes persist on refresh.  

Things that I will work on later:
- discarding changes 
- creating a new event

 Closes #82 (Should also close #109 )

### CODE REVIEW

**Review by josiahsrc — APPROVED** [review]
Code looks good. I'll pull down these changes and do a QA review and let you know

**Comment by josiahsrc** [comment]
# QA Review

Ok, so doing some QA. Here is what I found:

## 1. Event ID not passed to new event URL

Steps to reproduce:
0. Log in
1. Press the `Add Event` button to create a new event. Once navigated to the event edit page, notice at the URL of the page, `https://localhost:3000/event-edit`, there is no event ID visible.
2. Edit the title field to say `EVENT A` and press the `save` button to confirm changes
3. Refresh the page (the fields should go blank)
4. Edit the title field to say `EVENT B` and press the `save` button to confirm changes

There will be two events, `EVENT A` and `EVENT B` created. Refreshing the page should instead keep the state of `EVENT A.` I believe this is because there is no ID passed into the url, so there's nothing to hold onto after refreshing.

## 2. Error when saving an empty title, Path `title` is required.

Steps to reproduce:
0. Log in
1. Create a new event
2. Click the edit event title button (the pencil icon)
3. Leave the title empty
4. Click the check mark
5. Hit save event button

Once this is done, the server will stop running and produce the following error result (shown below). The backend should be able to accept empty titles, or perhaps we could just send "untitled event".

```
errors: {
    title: ValidatorError: Path `title` is required.
        at validate (/Users/josiahsaunders/school/CS428/project/server/node_modules/mongoose/lib/schematype.js:1222:13)
        at /Users/josiahsaunders/school/CS428/project/server/node_modules/mongoose/lib/schematype.js:1205:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (/Users/josiahsaunders/school/CS428/project/server/node_modules/mongoose/lib/schematype.js:1150:14)
        at /Users/josiahsaunders/school/CS428/project/server/node_modules/mongoose/lib/document.js:2439:18
        at processTicksAndRejections (node:internal/process/task_queues:75:11)
        at runNextTicks (node:internal/process/task_queues:62:3)
        at processImmediate (node:internal/timers:435:9) {
      properties: {
        validator: [Function (anonymous)],
        message: 'Path `title` is required.',
        type: 'required',
        path: 'title',
        value: ''
      },
      kind: 'required',
      path: 'title',
      value: '',
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
```

**Review by josiahsrc — CHANGES_REQUESTED** [review]
See QA comment above

**Comment by hokansom** [comment]
@josiahsrc Thanks for checking my code! I decided not to deal with creating a new event yet, so I didn't finish hashing out the details regarding that. The backend is the one who creates the eventId for a new event, so we don't technically have an id when we go to the new page, which is how the frontend knows whether to do a PUT or a POST.  

As for the empty title field, I didn't do any field validation on the frontend yet. I know that is bad coding practice, but we can work on adding validation as a future issue unless we want that right now as part of this task. @Clotonervo The backend should never crash, so we do probably want to fix that part. It's just a matter of do we only let people save on the frontend when the title is not empty, or do we want the backend to populate a placeholder title?

**Comment by josiahsrc** [comment]
Oh gotcha! Ok, we can disregard the `create-event` details then for now, but let's keep those issues on our radar as we get to implementing that.

The no field validation is probably fine for the demo, but the backend crash thing concerns me. Could we deal with that in this PR or should we push off fixing that for another PR? @hokansom  @Clotonervo

**Comment by hokansom** [comment]
@Clotonervo 
I'm assuming that this is the block of code that is the issue. req.body.title = "", so the code inside the if block isn't being executed. Do we want to fix this on this branch? Or would you like to make another branch?  
```
if (req.body.title == null) {
      //title is required error
      res.statusCode = 200
      res.send({
        success: false,
        message: "A title is required"
      });
    }
```

**Comment by Clotonervo** [comment]
Hmm that looks like to have gotten change. We don't need a title, but we do need the event ID. I can have it check for the eventID, and if there isn't one return that error. I'm not sure when that got changed but I will go get it working.

Did you say you don't have access to an event ID when creating an event? That might be an issue, and maybe we should have the POST /event endpoint return the eventID that was created? That way you have a reference on the frontend.

If you want me to fix it on another branch I will happily do that. Whatever it takes to keep you from being blocked.

**Comment by hokansom** [comment]
@Clotonervo You can fix it on this branch or another one (and I'll just merge your changes into this one).

As for the eventID information, if you want to return the new eventID in the POST that would be great. It's included as part of the message, but I don't want to have to parse it out of a string.

**Comment by Clotonervo** [comment]
I just made the changes, currently testing it with postman just to make sure though.

**Comment by Clotonervo** [comment]
Ok, after testing on Postman, this should work ok. If you run into other issues just let me know. 

I think I figured out what the server crashing is. Apparently when you do a res.send, you need to also return from the function so no other code gets executed. Not sure why this just showed up now, but I'm glad we caught it. I will make this another branch to fix it, and I'll get it in before demo hopefully.

**Review by josiahsrc — APPROVED** [review]
lgtm

**Pull request merged**
