### PR TITLE
Fix backend

### PR DESCRIPTION
**Pull request by Clotonervo**
* Deleted invitees, should just reference viewers
* Fixed issue with the isCollaborator token not being returned correctly
* Updated database_script.js to reflect changes. Now has a separate list of viewers and collaborators.
* Was tested with Postman, I will get to testing with frontend later tonight.

### CODE REVIEW

**Comment by Clotonervo** [comment]
@hokansom If there are other problems I didn't fix or forgot to include let me know and I will have them updated by tonight.

**Comment by hokansom** [comment]
@Clotonervo  Does this also fix the GET /events endpoint so that isCollaborator is being returned?

Also, if it's too not much work, could we get some colors and descriptions added to the sample events? 
Here are some colors that you could use. 

 "#8be4d2" (theme color)
 "#FFA089" (orange)
 "#FFD958" (yellow)
 "#E7FF89" (green)
"#FF8989" (pink)

**Comment by Clotonervo** [comment]
Yes It should fix the GET /events, I tested it today and it was correctly returning the data. I will add the colors now

**Review by hokansom — APPROVED** [review]
I think that it looks good

**Pull request merged**
